[project]
name = "genai-trials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-community>=0.3.16",
    "langchain-core>=0.3.33",
    "langchain-ollama>=0.2.3",
    "streamlit>=1.41.1",
]
